spring:
  application:
    name: gnw-cloud-provider-prod
  rabbitmq:
    host: localhost
    port: 5672
    username: letrain
    password: 123456
server:
  port: 8790
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9800/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
    lease-expiration-duration-in-seconds: 15 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    prefer-ip-address: true
    # 2.0版本以上的要改成 ip-address   以下的是 ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${server.port}